//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANHBAO
    {
        public int MACANHBAO { get; set; }
        public string MAKHO { get; set; }
        public string MASP { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public bool DAXEM { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
