//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public KHO()
        {
            this.KIEMKEKHOes = new HashSet<KIEMKEKHO>();
            this.PHANCONG_KHO = new HashSet<PHANCONG_KHO>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
            this.PHIEUXUATs1 = new HashSet<PHIEUXUAT>();
            this.TONKHOes = new HashSet<TONKHO>();
        }
    
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
        public string DIADIEM { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<KIEMKEKHO> KIEMKEKHOes { get; set; }
        public virtual ICollection<PHANCONG_KHO> PHANCONG_KHO { get; set; }
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs1 { get; set; }
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
    }
}
