//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEMKEKHO
    {
        public KIEMKEKHO()
        {
            this.CT_KIEMKE = new HashSet<CT_KIEMKE>();
        }
    
        public string MAKIEMKE { get; set; }
        public string MAKHO { get; set; }
        public string MATK { get; set; }
        public System.DateTime NGAYKIEMKE { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<CT_KIEMKE> CT_KIEMKE { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
