//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG_KHO
    {
        public string MATK { get; set; }
        public string MAKHO { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
