//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public PHIEUNHAP()
        {
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
        }
    
        public string MAPN { get; set; }
        public string MANSX { get; set; }
        public string MAKHO { get; set; }
        public string MATK { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public decimal TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
