//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        public PHIEUXUAT()
        {
            this.CT_PHIEUXUAT = new HashSet<CT_PHIEUXUAT>();
        }
    
        public string MAPX { get; set; }
        public string MAKHO { get; set; }
        public string MAKHONHAN { get; set; }
        public string MATK { get; set; }
        public System.DateTime NGAYXUAT { get; set; }
        public decimal TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual KHO KHO1 { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
