//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLI_KHOHANGEntities : DbContext
    {
        public QUANLI_KHOHANGEntities()
            : base("name=QUANLI_KHOHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_KIEMKE> CT_KIEMKE { get; set; }
        public DbSet<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public DbSet<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public DbSet<DONVITINH> DONVITINHs { get; set; }
        public DbSet<KHO> KHOes { get; set; }
        public DbSet<KIEMKEKHO> KIEMKEKHOes { get; set; }
        public DbSet<LOAIHANG> LOAIHANGs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<NHASANXUAT> NHASANXUATs { get; set; }
        public DbSet<NHATKY> NHATKies { get; set; }
        public DbSet<PHANCONG_KHO> PHANCONG_KHO { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<TONKHO> TONKHOes { get; set; }
        public DbSet<VAITRO> VAITROes { get; set; }
        public DbSet<V_BAOCAO_XUAT> V_BAOCAO_XUAT { get; set; }
        public DbSet<V_NHATKY_DANGNHAP> V_NHATKY_DANGNHAP { get; set; }
        public DbSet<V_NHATKY_THAOTAC> V_NHATKY_THAOTAC { get; set; }
    }
}
