//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CT_KIEMKE = new HashSet<CT_KIEMKE>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
            this.CT_PHIEUXUAT = new HashSet<CT_PHIEUXUAT>();
            this.TONKHOes = new HashSet<TONKHO>();
            this.CANHBAOs = new HashSet<CANHBAO>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MADVT { get; set; }
        public string MALOAI { get; set; }
        public string MANSX { get; set; }
        public decimal DONGIA { get; set; }
        public int MUCTONTOITHIEU { get; set; }
    
        public virtual ICollection<CT_KIEMKE> CT_KIEMKE { get; set; }
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual ICollection<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
        public virtual ICollection<CANHBAO> CANHBAOs { get; set; }
    }
}
