//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.KIEMKEKHOes = new HashSet<KIEMKEKHO>();
            this.NHATKies = new HashSet<NHATKY>();
            this.PHANCONG_KHO = new HashSet<PHANCONG_KHO>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
            this.VAITROes = new HashSet<VAITRO>();
        }
    
        public string MATK { get; set; }
        public string TENTK { get; set; }
        public string MATKHAU { get; set; }
        public string MANV { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual ICollection<KIEMKEKHO> KIEMKEKHOes { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ICollection<NHATKY> NHATKies { get; set; }
        public virtual ICollection<PHANCONG_KHO> PHANCONG_KHO { get; set; }
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual ICollection<VAITRO> VAITROes { get; set; }
    }
}
