//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BANGTHONGKE_TONKHO
    {
        public string Kho { get; set; }
        public string Mã_SP { get; set; }
        public string Tên_sản_phẩm { get; set; }
        public string Loại_hàng { get; set; }
        public int Số_lượng_tồn { get; set; }
        public decimal Đơn_giá { get; set; }
        public Nullable<decimal> Giá_trị_tồn_kho { get; set; }
    }
}
