//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CANHBAO_TONKHO
    {
        public string TENKHO { get; set; }
        public string TENSP { get; set; }
        public int SOLUONGTON { get; set; }
        public int MUCTONTOITHIEU { get; set; }
        public string TRANGTHAI { get; set; }
    }
}
