//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NHATKY_THAOTAC_HETHONG
    {
        public int ID { get; set; }
        public string MATK { get; set; }
        public string TENTK { get; set; }
        public string HANHDONG { get; set; }
        public string DOITUONG { get; set; }
        public System.DateTime THOIGIAN { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    }
}
