//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TAIKHOAN_VAITRO
    {
        public string MATK { get; set; }
        public string TENTK { get; set; }
        public string TENNV { get; set; }
        public string EMAIL { get; set; }
        public string TENVT { get; set; }
        public string MAKHO { get; set; }
        public bool TRANGTHAI { get; set; }
    }
}
