//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_THONGKE_HOATDONG_NGUOIDUNG
    {
        public string TENTK { get; set; }
        public string TENNV { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> SO_LAN_THANH_CONG { get; set; }
        public Nullable<int> SO_LAN_THAT_BAI { get; set; }
        public Nullable<System.DateTime> LAN_CUOI_HOATDONG { get; set; }
    }
}
